### ISSUE TITLE
Data Upload of large files is failing

### ISSUE THREAD

**Issue by Daniellappv** [datopian/datapub-nhs#14]
Size of NHS files vary between 5.8 GB and 6.3 GB, Avg is roughly 6.1 GB

We tested uploading a 6 GB file via the GUI but it's crashing, see screenshot

![image](https://user-images.githubusercontent.com/45828069/99433902-d127d500-2916-11eb-8dcc-778cd02b02dc.png)

Another test with a 6.3 GB file // with Network requests/responses and errors when uploading

![image](https://user-images.githubusercontent.com/45828069/99645346-c3c63400-2a57-11eb-998c-575dc6c84f4e.png)

10 mins later

![image](https://user-images.githubusercontent.com/45828069/99645364-c7f25180-2a57-11eb-8ca0-93929724623c.png)

20 mins later

![image](https://user-images.githubusercontent.com/45828069/99645415-dccee500-2a57-11eb-8214-02774c7a21f5.png)

Error: **"Paused before potential out-of-memory crash"**

## Acceptance

* [ ] Upload via GUI should work for their max-sized files (6.3 GB)
* [ ] Shouldn’t be slower than the current solution (uploading files manually to the bucket)

**Comment by mariorodeghiero** [comment]
**Just a note:**

- this failed before the upload request, I think is about generating a hash or some step after this.

**Comment by mariorodeghiero** [comment]
@Daniellappv how the root cause is in datapub repository I opened the issue there. You can check here https://github.com/datopian/datapub/issues/78

**Comment by risenW** [comment]
> @Daniellappv how the root cause is in datapub repository I opened the issue there. You can check here [datopian/datapub#78](https://github.com/datopian/datapub/issues/78)

@mariorodeghiero The cause is actually coming from frictionless.js. Check out this pull [here](https://github.com/frictionlessdata/frictionless-js/pull/114)
